server:
  port: 8083
spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/alejorcode/microservices-tuto
          search-paths: config-data
          
